import Head from 'next/head'
import Image from 'next/image'
import {blogPosts} from '../../lib/data';

export default function BlogPage({ title, date, content }) {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h2 className="font-bold text-lg my-3 border-b-2 bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-500">{ title }</h2>
                <div>
                    { content }
                </div>
            </main>
        </div>
    )
}

export async function getStaticProps(context) {
    console.log(context)
    const {params} = context;
    return {
        props: blogPosts.find(item => item.slug === params.slug), // will be passed to the page component as props
    };
}

export async function getStaticPaths() {
    return {
        paths: blogPosts.map((item) => ({
            params: {
                slug: item.slug
            },
        })),
        fallback: false,
    };
}
