import Head from 'next/head';
import Image from 'next/image';
import Link from "next/link";
import { format, parseISO, add } from 'date-fns';
import { blogPosts } from '../lib/data';


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Hello
        </h1>
          <div className="space-y-4">
              {blogPosts.map((item) => (
                <BlogListItem key={item.slug } {...item } />
              ))}
          </div>
      </main>
    </div>
  )
}

function BlogListItem({ slug, title, date, content }) {
    return(
        <div className="border border-black-2 shadow rounded-md p-4 hover:shadow-md transition duration-300 ease-in">
            <div>
                <Link href={`/blog/${slug}`}>
                    <a className="text-lg font-bold"> { title } </a>
                </Link>
            </div>
            <div className="text-gray-600 text-sm">{format(parseISO(date), 'MMMM do, uuu')}</div>
            <div>{content}</div>
        </div>
    )
}