import Head from 'next/head'
import Image from 'next/image'

export default function Services() {
    return (
        <div>
            <Head>
                <title>Services</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>
                    Services
                </h1>
            </main>
        </div>
    )
}
